export const sidebar1 = {
  position: "absolute",
  top: "-100vh",
  left: "0",
  display: "flex",
  flexDirection: "column",
  justifyContent: "center",
  alignItems: "center",
  height: "100vh",
  width: "100%",
  backgroundColor: "white",
  transition: "0.4s ease-out",
  zIndex: "1",
};
export const sidebar2 = {
  position: "fixed",
  top: "0",
  left: "0",
  right: "0",
  display: "flex",
  flexDirection: "column",
  justifyContent: "center",
  alignItems: "center",
  height: "100vh",
  width: "100%",
  backgroundColor: "white",
  transition: "0.4s ease-out",
  zIndex: "1",
};
